plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
email: contact@shyaman.me
linkedin: https://www.linkedin.com/in/shyamanj
scholar: https://scholar.google.com/citations?user=LJn7bbAAAAAJ&hl=en
flickr: https://www.flickr.com/photos/shyaman321
github: https://github.com/shyaman/
facebook: https://www.facebook.com/shyaman.madhawa/
youtube: https://www.youtube.com/channel/UChoPlHOdGXodB_2D2yNOf2w
currentTitle: PhD Student (Computer Science) and Graduate Research Assistant |
  B.Sc. Eng (Hons), AMIESL
bio: I'm a passionate data science enthusiast with a keen interest in
  bioinformatics and computational biology. Beyond the world of data, I find joy
  in exploring new places and capturing precious moments with my loved ones.
repository: shyaman/shyaman.github.io
url: https://www.shyaman.me
defaults:
  - scope:
      path: admin/**
    values:
      sitemap: false
cv: https://drive.google.com/file/d/17XYCQ3qN6mOXZ4e3YI1cslJaNHPc0Tzs/view?usp=sharing
orcid: https://orcid.org/0000-0003-0522-3353
twitter: https://twitter.com/shyaman_madhawa
instagram: https://www.instagram.com/shyaman_j/
timezone: Asia/Colombo
pinterest: https://www.pinterest.com/shyaman_j/
